version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.production
    depends_on:
      - db
  db:
    image: postgres:17.6-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=learning_django
      - POSTGRES_PASSWORD=learning_django
      - POSTGRES_DB=learning_django

volumes:
  postgres_data:
