version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 tennis_club.wsgi:application
    volumes:
      - .:/usr/src/app/
      - media_data:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.production
    depends_on:
      - db

  db:
    image: postgres:17.6-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tennis_club
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tennis_club

  nginx:
    image: nginx:1.28.0-bookworm
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/usr/src/app/staticfiles
      - media_data:/usr/src/app/media

volumes:
  postgres_data:
  media_data:
