# Generated by Django 5.2.7 on 2025-10-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
    ]
