# Generated by Django 5.2.7 on 2025-10-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
